services:
  postgres:
    image: postgres:15
    container_name: tv_show_demo_db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/install-pgtap.sql:/docker-entrypoint-initdb.d/02-install-pgtap.sql
      # Mount tests directory for easy access from container
      - ./tests:/app/tests:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: