name: PR Database Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write
  pages: write
  id-token: write

jobs:
  test:
    name: Run BDD Tests
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
          # Install Allure CLI
          curl -o allure-2.24.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          sudo tar -zxvf allure-2.24.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Neon Branch
        id: create_neon_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Run database migrations
        run: |
          # Apply the schema to the Neon branch database using the full connection URL
          psql "${{ steps.create_neon_branch.outputs.db_url_with_pooler }}" -f schema.sql

      - name: Run BDD tests
        env:
          # Use the full database URL for Python connection
          DATABASE_URL: ${{ steps.create_neon_branch.outputs.db_url_with_pooler }}
        run: |
          # Run pytest with BDD tests and generate both JUnit XML and Allure reports
          pytest -v --tb=short \
            --junitxml=test-results.xml \
            --alluredir=allure-results \
            --allure-link-pattern=issue:https://github.com/${{ github.repository }}/issues/{} \
            --allure-link-pattern=test_case:https://github.com/${{ github.repository }}/blob/${{ github.sha }}/features/{}

      - name: Download previous Allure history
        if: always()
        continue-on-error: true
        run: |
          # Create allure-results directory if it doesn't exist
          mkdir -p allure-results
          
          # Try to download previous Allure history from GitHub Pages
          echo "🔍 Checking for previous test history..."
          
          # Download the previous allure report to extract history
          if curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/history.json" -o /tmp/history.json; then
            echo "✅ Found previous history.json"
            mkdir -p allure-results/history
            
            # Download all history files
            curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/history.json" -o allure-results/history/history.json || true
            curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/history-trend.json" -o allure-results/history/history-trend.json || true
            curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/duration-trend.json" -o allure-results/history/duration-trend.json || true
            curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/retry-trend.json" -o allure-results/history/retry-trend.json || true
            curl -f -s "https://demithras.github.io/tv-show-intervals-demo/pr-${{ github.event.number }}/history/categories-trend.json" -o allure-results/history/categories-trend.json || true
            
            echo "✅ Previous test history restored"
            ls -la allure-results/history/ || true
          else
            echo "ℹ️ No previous history found - this will be the first run for trend analysis"
          fi

      - name: Generate Allure Report with History
        if: always()
        run: |
          # Generate Allure HTML report with history (don't use --clean to preserve history)
          echo "📊 Generating Allure report with test-level history..."
          allure generate allure-results -o allure-report
          
          # Verify history was properly integrated
          if [ -f "allure-report/history/history.json" ]; then
            echo "✅ Test history successfully integrated into report"
            echo "📈 History file size: $(wc -c < allure-report/history/history.json) bytes"
          else
            echo "ℹ️ No history file in generated report (first run)"
          fi
          
          # Add environment information with more details
          cat > allure-report/environment.properties << EOF
          Database.Host=${{ steps.create_neon_branch.outputs.db_url_with_pooler }}
          Python.Version=3.11
          Test.Framework=pytest-bdd
          CI.Provider=GitHub Actions
          PR.Number=${{ github.event.number }}
          Branch.Name=${{ github.head_ref }}
          Commit.SHA=${{ github.sha }}
          Run.Number=${{ github.run_number }}
          Run.Attempt=${{ github.run_attempt }}
          Timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          Repository=${{ github.repository }}
          EOF
          
          # Add test execution metadata for better history tracking
          if [ -f "allure-report/widgets/summary.json" ]; then
            echo "📊 Test summary available for trend analysis"
          fi
          
          echo "✅ Allure report generated with per-test history tracking"

      - name: Upload Allure Results with History
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-pr-${{ github.event.number }}-run-${{ github.run_number }}
          path: allure-results/
          retention-days: 30

      - name: Upload Allure Report with History
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-pr-${{ github.event.number }}-run-${{ github.run_number }}
          path: allure-report/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: pr-${{ github.event.number }}
          keep_files: true
          force_orphan: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Allure report for PR #${{ github.event.number }} (Run #${{ github.run_number }})'

      - name: Generate Global History Report
        if: always() && github.event.action != 'closed'
        run: |
          # Create a global history index page
          mkdir -p global-history
          
          cat > global-history/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Test History - TV Show Intervals Demo</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .header { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
                  .pr-link { display: block; padding: 10px; margin: 5px 0; background: #e8f4fd; border-left: 4px solid #0366d6; text-decoration: none; color: #0366d6; border-radius: 4px; }
                  .pr-link:hover { background: #cce8ff; }
                  .timestamp { color: #666; font-size: 0.9em; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>🧪 TV Show Intervals Demo - Test History</h1>
                  <p>Browse Allure test reports for all pull requests</p>
              </div>
              
              <h2>📊 Available Test Reports</h2>
              <div id="reports">
                  <a href="pr-${{ github.event.number }}/" class="pr-link">
                      📋 PR #${{ github.event.number }} - Latest Run
                      <div class="timestamp">Run #${{ github.run_number }} • ${{ github.head_ref }} • $(date -u +"%Y-%m-%d %H:%M UTC")</div>
                  </a>
              </div>
              
              <h2>🔍 Report Features</h2>
              <ul>
                  <li>📈 <strong>Trends</strong>: Test execution history and performance over time</li>
                  <li>🎯 <strong>BDD Scenarios</strong>: Gherkin features with step-by-step execution</li>
                  <li>📊 <strong>Analytics</strong>: Test distribution, timing, and failure analysis</li>
                  <li>📎 <strong>Attachments</strong>: Database queries, program data, and debug info</li>
                  <li>🏷️ <strong>Categories</strong>: Organized by features and test types</li>
              </ul>
          </body>
          </html>
          EOF

      - name: Deploy Global History Index
        if: always() && github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./global-history
          destination_dir: .
          keep_files: true
          force_orphan: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update global test history index'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-pr-${{ github.event.number }}
          path: test-results.xml

      - name: Comment test results on PR
        uses: dorny/test-reporter@v1
        if: always()
        continue-on-error: true
        with:
          name: BDD Test Results
          path: test-results.xml
          reporter: java-junit

      - name: Parse and comment test results with Allure link
        if: always()
        run: |
          if [ -f test-results.xml ]; then
            # Extract test summary from JUnit XML
            TOTAL_TESTS=$(grep -o 'tests="[^"]*"' test-results.xml | grep -o '[0-9]*' | head -1)
            FAILURES=$(grep -o 'failures="[^"]*"' test-results.xml | grep -o '[0-9]*' | head -1)
            ERRORS=$(grep -o 'errors="[^"]*"' test-results.xml | grep -o '[0-9]*' | head -1)
            
            # Set defaults if not found
            TOTAL_TESTS=${TOTAL_TESTS:-0}
            FAILURES=${FAILURES:-0}
            ERRORS=${ERRORS:-0}
            
            PASSED=$((TOTAL_TESTS - FAILURES - ERRORS))
            
            # Determine status
            if [ $FAILURES -gt 0 ] || [ $ERRORS -gt 0 ]; then
              STATUS="❌ Tests failed"
              ADDITIONAL_TEXT="Some tests are failing. This might be expected if testing the CI/CD pipeline with intentional failures."
            else
              STATUS="✅ All tests passed"
              ADDITIONAL_TEXT=""
            fi
            
            # GitHub Pages URL for Allure report
            ALLURE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}"
            HISTORY_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
            
            # Create comment body as JSON for API
            cat > comment-payload.json << EOF
          {
            "body": "## 🧪 BDD Test Results (Run #${{ github.run_number }})\n\n**Summary:**\n- ✅ **Passed:** ${PASSED}\n- ❌ **Failed:** ${FAILURES}\n- 🔥 **Errors:** ${ERRORS}\n- 📊 **Total:** ${TOTAL_TESTS}\n\n**Status:** ${STATUS}\n\n${ADDITIONAL_TEXT}\n\n## 📊 Interactive Reports\n\n- 🎯 **[View Latest Allure Report](${ALLURE_URL})** - Full test results with history trends\n- 📈 **[Browse All Test History](${HISTORY_URL})** - Historical reports across all PRs\n- 📁 **[Download Test Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})** - Raw results and logs\n\n## 📈 History Features\n\n- **Trends**: Performance and stability over time\n- **Retries**: Flaky test detection and analysis  \n- **Duration**: Execution time trends and bottlenecks\n- **Categories**: Failure pattern analysis\n\n<details>\n<summary>🔍 View JUnit XML summary</summary>\n\n\`\`\`xml\n$(cat test-results.xml | head -20 | sed 's/"/\\"/g')\n\`\`\`\n\n</details>"
          }
          EOF
            
            # Post comment using GitHub API
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{ github.event.number }}/comments" \
              -d @comment-payload.json
              
            echo "Posted test results comment with Allure link to PR #${{ github.event.number }}"
            echo "Allure report will be available at: ${ALLURE_URL}"
          else
            echo "No test results file found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    name: Delete Neon Branch
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}